package quva.postprocessing;

/**This interface allows customizing the output generated by {@link OutputGrid}*/
public interface SingleBitOutput {
	/**Describes how the single qubits are outputed by {@link OutputGrid}.
	 * @param value value of the qubits (1 or 0)
	 * @param pos number of the qubit
	 * @param x column in the grid
	 * @param y row in the grid
	 * @return String to be appended*/
	public String genString(int value,int pos,int x,int y) ;
}
