/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dwas_main_MinorMinerImplementation */

#ifndef _Included_dwas_main_MinorMinerImplementation
#define _Included_dwas_main_MinorMinerImplementation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dwas_main_MinorMinerImplementation
 * Method:    find_Embedding
 * Signature: (II[I[I[I[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_dwas_main_MinorMinerImplementation_find_1Embedding
  (JNIEnv *, jobject, jint, jint, jintArray, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
